Repository andersonmadeira/clock, pull requests merged in 2020-11, with the labels that each got.

#10 Update and Display time on screen
  index.html
  script.js
  style.css
Labels: enhancement

#12 Basic code optimization for css and js
  script.js
  style.css
Labels: enhancement

#16 Localized time display
  script.js
Labels: enhancement

#25 Auto-update feature fixed
  script.js
Labels: bug

#26 fix: Fixed horizontal and vertical alignment
  style.css
Labels: enhancement

#27 Improved documentation
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement
